### PR TITLE
Update header nav styles

### PR DESCRIPTION
**Pull request by fantasticmrdavid**
Update the forum nav to match blog and Premium.

screen shot 2015-11-10 at 11 22 12 am

Hover states
screen shot 2015-11-10 at 11 22 25 am
screen shot 2015-11-10 at 11 22 36 am
screen shot 2015-11-10 at 11 25 26 am
screen shot 2015-11-10 at 11 24 50 am

Dropdown active state
screen shot 2015-11-10 at 11 23 12 am

Mobile
screen shot 2015-11-10 at 3 36 27 pm

### CODE REVIEW

**Comment by kellec** [comment]
:+1: Looks good, how does it look on mobile?

**Comment by fantasticmrdavid** [comment]
Current prod mobile is a mess. Will fix it in another pr.

**Comment by fantasticmrdavid** [comment]
Mobile fixes added. Note that the plugin applies mobile styles based on user agent.

**Comment by BradDenver** [comment]
:+1:

**Pull request merged**
